/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.FuncionDTO;
import dtos.GeneroDTO;
import dtos.PeliculaDTO;
import dtos.SalaDTO;
import dtos.SucursalDTO;
import enumeradores.Clasificaciones;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import negocio.IFuncionBO;
import negocio.IPeliculaBO;
import negocio.ISalaBO;
import negocio.ISucursalBO;
import negocio.NegocioException;
import negocio.SalaBO;
import persistencia.ConexionBD;
import persistencia.IConexionBD;
import persistencia.ISalaDAO;
import persistencia.ISucursalDAO;
import persistencia.SalaDAO;
import persistencia.SucursalDAO;
import utilerias.Herramientas;
import static utilerias.Herramientas.getComboBoxItems;

/**
 *
 * @author rramirez
 */
public class FrmAgregarFuncion extends javax.swing.JFrame {

    private IFuncionBO funcionBO;
    private PeliculaDTO pelicula;
    private SalaDTO sala;
    SucursalDTO sucursal;
    private boolean modoEstreno;
    private Locale[] locales;
    private String ruta = "";

    /**
     * Creates new form FrmAgregarCliente
     */
    public FrmAgregarFuncion(IFuncionBO funcionBO, PeliculaDTO pelicula, SalaDTO sala, SucursalDTO sucursal) {
        initComponents();
        this.funcionBO = funcionBO;
        this.pelicula = pelicula;
        this.sala = sala;
        this.sucursal = sucursal;
        locales = Locale.getAvailableLocales();
        this.llenarComboDias();
        metodoMostrarDatos();
        configuracionFrame();

    }

    public void metodoMostrarDatos() {
        lblTitulo.setText(Herramientas.textoConSaltosLinea(pelicula.getTitulo(), 5));
        lblSucursal.setText(sucursal.getNombre());
        lblSala.setText(sala.getNombre());
        ImageIcon icon = new ImageIcon(pelicula.getCartel());
        Image scaledImage = icon.getImage().getScaledInstance(279, 382, Image.SCALE_SMOOTH);
        lblImagenCartel.setIcon(new ImageIcon(scaledImage));

    }

    public void configuracionFrame() {
        this.setTitle("Agregar Funciones " + sucursal.getNombre());
        this.setResizable(false);
        this.setSize(1280, 780);
        this.setLocationRelativeTo(null);
    }

    ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSpinField1 = new com.toedter.components.JSpinField();
        jPanel1 = new javax.swing.JPanel();
        LblMaterno = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        LblPaterno2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblImagenCartel = new javax.swing.JLabel();
        cbDias = new javax.swing.JComboBox<>();
        LblPaterno5 = new javax.swing.JLabel();
        jSpinPrecio = new javax.swing.JSpinner();
        LblPaterno7 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();
        rbtnEstreno = new javax.swing.JRadioButton();
        lblSucursal = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 44, 99));
        jPanel1.setToolTipText("");

        LblMaterno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblMaterno.setForeground(new java.awt.Color(255, 255, 255));
        LblMaterno.setText("Hora");

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        LblPaterno2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LblPaterno2.setForeground(new java.awt.Color(255, 255, 255));
        LblPaterno2.setText("Agregar Funcion");

        jPanel2.setBackground(new java.awt.Color(33, 36, 59));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        lblImagenCartel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3212c44f6aca4bc69d467d4614e6f3dc 1.png"))); // NOI18N

        cbDias.setBackground(new java.awt.Color(33, 36, 59));
        cbDias.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbDias.setForeground(new java.awt.Color(255, 255, 255));

        LblPaterno5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblPaterno5.setForeground(new java.awt.Color(255, 255, 255));
        LblPaterno5.setText("Dia");

        LblPaterno7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LblPaterno7.setForeground(new java.awt.Color(255, 255, 255));
        LblPaterno7.setText("Precio");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Top Gun Maverick");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Line 7.png"))); // NOI18N

        timePicker1.setBackground(new java.awt.Color(33, 36, 59));

        rbtnEstreno.setText("Modo Estreno");
        rbtnEstreno.setBackground(new java.awt.Color(36, 44, 99));
        rbtnEstreno.setContentAreaFilled(false);
        rbtnEstreno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtnEstreno.setForeground(new java.awt.Color(255, 255, 255));

        lblSucursal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSucursal.setForeground(new java.awt.Color(255, 255, 255));
        lblSucursal.setText("Sucursal");

        lblSala.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSala.setForeground(new java.awt.Color(255, 255, 255));
        lblSala.setText("Sala");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagenCartel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPaterno2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(LblPaterno5)
                                            .addGap(219, 219, 219))
                                        .addComponent(cbDias, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LblPaterno7)
                                        .addComponent(jSpinPrecio)
                                        .addComponent(LblMaterno)
                                        .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(rbtnEstreno)))
                                .addGap(251, 251, 251))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblPaterno5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(LblPaterno7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(rbtnEstreno)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(LblPaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagenCartel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        IConexionBD conexion = new ConexionBD();
        ISalaDAO salaDAO = new SalaDAO(conexion);
        ISalaBO salaBO = new SalaBO(salaDAO);

        FrmAdminFuncion funcion = new FrmAdminFuncion(funcionBO, salaBO, sucursal, pelicula);
        funcion.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // Validation
        if (timePicker1.getText().isEmpty()
                || jSpinPrecio.getValue() == null
                || cbDias.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(this, "Por favor ingrese todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;  // Exit if validation fails
        }

        // Creating new FuncionDTO
        FuncionDTO funcion = new FuncionDTO();

        // Setting the 'dia'
        funcion.setDia((String) cbDias.getSelectedItem());

        // Set hora based on 'modoEstreno'
        if (modoEstreno) {
            funcion.setHora(LocalTime.MIDNIGHT);  // Midnight if estreno mode
        } else {
            funcion.setHora(timePicker1.getTime());  // Get the selected time from timePicker
        }

        // Setting 'precio' from jSpinPrecio
        BigDecimal precio = BigDecimal.valueOf(((Number) jSpinPrecio.getValue()).doubleValue());
        funcion.setPrecion(precio);

        // Setting sala and pelicula IDs
        funcion.setIdSala(sala.getId());
        funcion.setIdPelicula(pelicula.getId());

        // Success message
        // Save the FuncionDTO using the business object
        try {
            funcionBO.guardar(funcion);
            JOptionPane.showMessageDialog(this, "Funcion agregada con exito!");

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al agregar la pelicula. Por favor, intente nuevamente y revise los horarios.", "Error", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void llenarComboDias() {

        String[] daysOfWeek = {
            "Lunes",
            "Martes",
            "Miércoles",
            "Jueves",
            "Viernes",
            "Sábado",
            "Domingo"
        };

        for (String day : daysOfWeek) {
            cbDias.addItem(day); // Add each day to the combo box
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel LblMaterno;
    private javax.swing.JLabel LblPaterno2;
    private javax.swing.JLabel LblPaterno5;
    private javax.swing.JLabel LblPaterno7;
    private javax.swing.JComboBox<String> cbDias;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JSpinner jSpinPrecio;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblImagenCartel;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbtnEstreno;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables

}
