/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import dtos.ClienteDTO;
import dtos.FuncionDTO;
import dtos.PeliculaDTO;
import dtos.SucursalDTO;
import enumeradores.MetodosDePago;
import java.awt.Desktop;
import com.itextpdf.text.Image;
import dtos.CiudadDTO;
import dtos.SalaDTO;
import dtos.VentaDTO;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import negocio.CiudadBO;
import negocio.FuncionBO;
import negocio.ICiudadBO;
import negocio.IFuncionBO;
import negocio.IPeliculaBO;
import negocio.ISalaBO;
import negocio.ISucursalBO;
import negocio.ITicketBO;
import negocio.IVentaBO;
import negocio.NegocioException;
import negocio.PeliculaBO;
import negocio.SucursalBO;
import negocio.TicketBO;
import persistencia.CiudadDAO;
import persistencia.ConexionBD;
import persistencia.FuncionDAO;
import persistencia.ICiudadDAO;
import persistencia.IConexionBD;
import persistencia.IFuncionDAO;
import persistencia.IPeliculaDAO;
import persistencia.ISucursalDAO;
import persistencia.ITicketDAO;
import persistencia.PeliculaDAO;
import persistencia.SucursalDAO;
import persistencia.TicketDAO;

/**
 *
 * @author carli
 */
public class FrmCompraBoleto extends javax.swing.JFrame {

    /**
     * Creates new form FrmCatalogos
     */
    private IVentaBO ventaBO;
    private PeliculaDTO pelicula;
    private ClienteDTO cliente;
    private FuncionDTO funcion;
    private SucursalDTO sucursal;
    private VentaDTO venta;
    private CiudadDTO ciudad;
    private SalaDTO sala;
    private int cantidadBoletos;

    public FrmCompraBoleto(IVentaBO ventaBO, PeliculaDTO pelicula, ClienteDTO cliente, FuncionDTO funcion, SucursalDTO sucursal, SalaDTO sala, CiudadDTO ciudad) {
        initComponents();
        this.ventaBO = ventaBO;
        this.pelicula = pelicula;
        this.cliente = cliente;
        this.funcion = funcion;
        this.sucursal = sucursal;
        this.sala = sala;
        this.ciudad = ciudad;
        this.cantidadBoletos = 0;
        setTitle("Comprar Boleto");
        setResizable(false);
        setLocationRelativeTo(null);
        metodosIniciales();
    }

    private void metodosIniciales() {
        llenarComboMetodosPago();
        cargarDetallesPelicula();
    }

    private void cargarDetallesPelicula() {
        lblTitulo.setText(utilerias.Herramientas.textoConSaltosLinea(pelicula.getTitulo(), 5));
        lblPaisOrigen.setText(pelicula.getPais());
        lblDuracion.setText(pelicula.getDuracion() + " minutos");
        lblClasificacion.setText(pelicula.getClasificacion());
        lblHorario.setText(funcion.getDia() + " " + funcion.getHora() + "-" + funcion.getHoraFinal());
        if (pelicula.getClasificacionDescripcion().length() < 3) {
            lblClasificacionDescripcion.setText(" " + pelicula.getClasificacionDescripcion());

        } else {
            lblClasificacionDescripcion.setText(pelicula.getClasificacionDescripcion());
        }
        ImageIcon icon = new ImageIcon(pelicula.getCartel());
        java.awt.Image scaledImage = icon.getImage().getScaledInstance(229, 353, java.awt.Image.SCALE_SMOOTH);
        btnCartel.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInicio = new utilerias.MenuButton();
        btnSucursales = new utilerias.MenuButton();
        btnBoletos = new utilerias.MenuButton();
        btnInbox = new utilerias.MenuButton();
        btnPerfil = new utilerias.MenuButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnCartel = new javax.swing.JButton();
        btnTrailer = new utilerias.MenuButton();
        panelConFondo6 = new utilerias.PanelConFondo();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelConFondo1 = new utilerias.PanelConFondo();
        jLabel6 = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        panelConFondo3 = new utilerias.PanelConFondo();
        jLabel4 = new javax.swing.JLabel();
        lblClasificacion = new javax.swing.JLabel();
        lblClasificacionDescripcion = new javax.swing.JLabel();
        lblPaisOrigen = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblHorario = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbMetodosPago = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        lblCantidadBoletos = new javax.swing.JLabel();
        btnSumarCantidad = new utilerias.MenuButton();
        btnRestarCantidad = new utilerias.MenuButton();
        btnCancelar = new utilerias.MenuButton();
        btnComprar = new utilerias.MenuButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(33, 36, 59));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 65));
        jPanel3.setLayout(new java.awt.GridLayout(1, 5, 50, 0));

        btnInicio.setBorderPainted(false);
        btnInicio.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioSelected.png"))); // NOI18N
        btnInicio.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inicio.png"))); // NOI18N
        btnInicio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioSelected.png"))); // NOI18N
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel3.add(btnInicio);

        btnSucursales.setBorderPainted(false);
        btnSucursales.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SucursalesSelected.png"))); // NOI18N
        btnSucursales.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sucursales.png"))); // NOI18N
        btnSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalesActionPerformed(evt);
            }
        });
        jPanel3.add(btnSucursales);

        btnBoletos.setBorderPainted(false);
        btnBoletos.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticketsSelected.png"))); // NOI18N
        btnBoletos.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tickets.png"))); // NOI18N
        btnBoletos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticketsSelected.png"))); // NOI18N
        btnBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletosActionPerformed(evt);
            }
        });
        jPanel3.add(btnBoletos);

        btnInbox.setBorderPainted(false);
        btnInbox.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inboxSelected.png"))); // NOI18N
        btnInbox.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inbox.png"))); // NOI18N
        btnInbox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inboxSelected.png"))); // NOI18N
        btnInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInboxActionPerformed(evt);
            }
        });
        jPanel3.add(btnInbox);

        btnPerfil.setBorderPainted(false);
        btnPerfil.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfilSelected.png"))); // NOI18N
        btnPerfil.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N
        btnPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfilSelected.png"))); // NOI18N
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel3.add(btnPerfil);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(36, 44, 99));
        jPanel4.setPreferredSize(new java.awt.Dimension(1280, 1280));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(36, 44, 99));

        jLabel1.setBackground(new java.awt.Color(36, 44, 99));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cinépolis_logo 1.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Line 7.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Top Gun Maverick");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addGap(113, 113, 113)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addGap(176, 176, 176))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(36, 44, 99));
        jPanel8.setPreferredSize(new java.awt.Dimension(1280, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(36, 44, 99));

        jPanel9.setBackground(new java.awt.Color(36, 44, 99));

        jPanel10.setBackground(new java.awt.Color(36, 44, 99));

        btnCartel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3212c44f6aca4bc69d467d4614e6f3dc 1.png"))); // NOI18N
        btnCartel.setBorderPainted(false);
        btnCartel.setContentAreaFilled(false);
        btnCartel.setPreferredSize(new java.awt.Dimension(229, 353));
        btnCartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartelActionPerformed(evt);
            }
        });

        btnTrailer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trailer.png"))); // NOI18N
        btnTrailer.setBorderPainted(false);
        btnTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrailerActionPerformed(evt);
            }
        });

        panelConFondo6.setPreferredSize(new java.awt.Dimension(169, 80));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/genero.png"))); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelConFondo6Layout = new javax.swing.GroupLayout(panelConFondo6);
        panelConFondo6.setLayout(panelConFondo6Layout);
        panelConFondo6Layout.setHorizontalGroup(
            panelConFondo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(27, 27, 27)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConFondo6Layout.setVerticalGroup(
            panelConFondo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo6Layout.createSequentialGroup()
                .addGroup(panelConFondo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConFondo6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel17))
                    .addGroup(panelConFondo6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        panelConFondo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelConFondo1.setPreferredSize(new java.awt.Dimension(169, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/duracion.png"))); // NOI18N

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setText("120 minutos");

        javax.swing.GroupLayout panelConFondo1Layout = new javax.swing.GroupLayout(panelConFondo1);
        panelConFondo1.setLayout(panelConFondo1Layout);
        panelConFondo1Layout.setHorizontalGroup(
            panelConFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(lblDuracion)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelConFondo1Layout.setVerticalGroup(
            panelConFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConFondo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDuracion)
                .addGap(27, 27, 27))
        );

        panelConFondo3.setPreferredSize(new java.awt.Dimension(169, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clasificacion.png"))); // NOI18N

        lblClasificacion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblClasificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblClasificacion.setText("R");

        lblClasificacionDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClasificacionDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblClasificacionDescripcion.setText("Adultos");

        javax.swing.GroupLayout panelConFondo3Layout = new javax.swing.GroupLayout(panelConFondo3);
        panelConFondo3.setLayout(panelConFondo3Layout);
        panelConFondo3Layout.setHorizontalGroup(
            panelConFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelConFondo3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClasificacionDescripcion)
                .addGap(33, 33, 33))
        );
        panelConFondo3Layout.setVerticalGroup(
            panelConFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConFondo3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClasificacion)
                    .addComponent(lblClasificacionDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblPaisOrigen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPaisOrigen.setForeground(new java.awt.Color(255, 255, 255));
        lblPaisOrigen.setText("Estados Unidos");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCartel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConFondo3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(panelConFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(panelConFondo6, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(lblPaisOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnTrailer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)))
                .addGap(20, 20, 20))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(btnCartel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTrailer, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConFondo6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jPanel16.setBackground(new java.awt.Color(36, 44, 99));

        lblHorario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(255, 255, 255));
        lblHorario.setText("Lunes 12:00 PM");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Metodo de Pago:");

        cbMetodosPago.setBackground(new java.awt.Color(33, 36, 59));
        cbMetodosPago.setForeground(new java.awt.Color(255, 255, 255));
        cbMetodosPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetodosPagoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Numero de Boletos:");

        lblCantidadBoletos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCantidadBoletos.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadBoletos.setText("00");

        btnSumarCantidad.setForeground(new java.awt.Color(255, 255, 255));
        btnSumarCantidad.setText("+");
        btnSumarCantidad.setBorderPainted(false);
        btnSumarCantidad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnSumarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarCantidadActionPerformed(evt);
            }
        });

        btnRestarCantidad.setForeground(new java.awt.Color(255, 255, 255));
        btnRestarCantidad.setText("-");
        btnRestarCantidad.setBorderPainted(false);
        btnRestarCantidad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnRestarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarCantidadActionPerformed(evt);
            }
        });

        btnCancelar.setBorderPainted(false);
        btnCancelar.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelarBoleto.png"))); // NOI18N
        btnCancelar.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelarBoleto.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnComprar.setBorderPainted(false);
        btnComprar.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprar.png"))); // NOI18N
        btnComprar.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprar.png"))); // NOI18N
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnRestarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCantidadBoletos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSumarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(cbMetodosPago, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbMetodosPago, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadBoletos)
                    .addComponent(btnSumarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)
                        .addContainerGap(551, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCartelActionPerformed

    private void btnTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrailerActionPerformed
        try {
            // Abre el enlace del tráiler en el navegador
            java.awt.Desktop.getDesktop().browse(new java.net.URI(pelicula.getLink_trailer()));
        } catch (java.io.IOException | java.net.URISyntaxException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir el tráiler: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrailerActionPerformed

    private void cbMetodosPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodosPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMetodosPagoActionPerformed

    private void btnSumarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarCantidadActionPerformed
        if (this.cantidadBoletos < this.funcion.getAsientosDisponibles()) {
            this.cantidadBoletos++;
            estadoPagina();  // Update the UI
        }

    }//GEN-LAST:event_btnSumarCantidadActionPerformed

    private void btnRestarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarCantidadActionPerformed
        if (this.cantidadBoletos > 0) {
            this.cantidadBoletos--;
            estadoPagina();  // Update the UI
        }

    }//GEN-LAST:event_btnRestarCantidadActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        IConexionBD conexion = new ConexionBD();

        IPeliculaDAO peliculaDAO = new PeliculaDAO(conexion);
        ICiudadDAO ciudadDAO = new CiudadDAO(conexion);
        ISucursalDAO sucursalDAO = new SucursalDAO(conexion);

        IPeliculaBO peliculaBO = new PeliculaBO(peliculaDAO);
        ICiudadBO ciudadBO = new CiudadBO(ciudadDAO);
        ISucursalBO sucursalBO = new SucursalBO(sucursalDAO);
        FrmCatalogoSucursal catalogo = new FrmCatalogoSucursal(peliculaBO, ciudadBO, sucursalBO, sucursal, cliente);
        catalogo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalesActionPerformed
        IConexionBD conexion = new ConexionBD();

        ICiudadDAO ciudadDAO = new CiudadDAO(conexion);
        ISucursalDAO sucursalDAO = new SucursalDAO(conexion);

        ICiudadBO ciudadBO = new CiudadBO(ciudadDAO);
        ISucursalBO sucursalBO = new SucursalBO(sucursalDAO);

        FrmSucursales sucursales = new FrmSucursales(ciudadBO, sucursalBO, sucursal, cliente);
        sucursales.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSucursalesActionPerformed

    private void btnBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletosActionPerformed
        IConexionBD conexionBD = new ConexionBD();
        ITicketDAO ticketDAO = new TicketDAO(conexionBD);
        ITicketBO ticketBO = new TicketBO(ticketDAO);
        FrmBoletos boletos = new FrmBoletos(ticketBO, cliente, sucursal);
        boletos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBoletosActionPerformed

    private void btnInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInboxActionPerformed
        FrmInbox inbox = new FrmInbox();
        inbox.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInboxActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        FrmConfiguracionPerfil perfil = new FrmConfiguracionPerfil();
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        IConexionBD conexion = new ConexionBD();
        IFuncionDAO funcionDAO = new FuncionDAO(conexion);
        IFuncionBO funcionBO = new FuncionBO(funcionDAO);
        FrmFuncionesPelicula funciones = new FrmFuncionesPelicula(funcionBO, pelicula, sucursal, cliente, ciudad);
        funciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        if (cbMetodosPago.getSelectedItem() == null || this.cantidadBoletos <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor,Seleccione un metodo de pago y cantidad valida.", "Campos Invalidos", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showOptionDialog(this,
                "¿Está seguro de que deseas Comprar una funcion para " + pelicula.getTitulo() + " a las " + funcion.getHora(),
                "Confirmación de eliminacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Cancelar", "Aceptar"},
                "Confirmar");

        // Si el usuario selecciona "Cancelar", no se hace nada
        if (confirmacion == JOptionPane.YES_OPTION) {
            return;
        }
        try {
            try {
                venta = new VentaDTO();
                venta.setCantidadBoleto(cantidadBoletos);
                venta.setMetodoPago((MetodosDePago) cbMetodosPago.getSelectedItem());
                venta.setIdCliente(cliente.getIdCliente());
                venta.setIdFuncion(funcion.getId());
                ventaBO.agregarVenta(this.venta);
            } catch (NegocioException ex) {
                Logger.getLogger(FrmCompraBoleto.class.getName()).log(Level.SEVERE, null, ex);
            }

            imprimirTicket();
        } catch (IOException ex) {
            Logger.getLogger(FrmCompraBoleto.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnComprarActionPerformed

    private void llenarComboMetodosPago() {
        for (MetodosDePago clasi : MetodosDePago.values()) {
            cbMetodosPago.addItem(clasi);
        }
    }

    private void estadoPagina() {
        // Update the label showing the quantity
        String cantidad = String.valueOf(this.cantidadBoletos);
        if (cantidad.length() == 1) {
            cantidad = "0" + cantidad;
        }

        lblCantidadBoletos.setText(cantidad);

        // Update button statuses
        estatusBotonAtras();
        estatusBotonSiguiente();
    }

    private void estatusBotonAtras() {
        // Disable the "restar" button if the quantity is 0
        btnRestarCantidad.setEnabled(this.cantidadBoletos > 0);
    }

    private void estatusBotonSiguiente() {
        // Disable the "sumar" button if the quantity is at max available seats
        btnSumarCantidad.setEnabled(this.cantidadBoletos < this.funcion.getAsientosDisponibles());
    }

    private void imprimirTicket() throws IOException {
        Document document = new Document();

        try {
            String fileName = "BoletoCine.pdf";
            PdfWriter.getInstance(document, new FileOutputStream(fileName));
            document.open();

            // Fuentes para el texto
            Font boldFont = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD);
            Font normalFont = new Font(Font.FontFamily.HELVETICA, 14, Font.NORMAL);

            // Título del establecimiento (Centrado con más espacios)
            Paragraph title = new Paragraph("******************************************************************\n"
                    + pelicula.getTitulo().toUpperCase() + "\n"
                    + this.sala.getNombre().toUpperCase() + "\n"
                    + this.funcion.getHora() + "-" + this.funcion.getHoraFinal() + "\n"
                    + "******************************************************************\n", boldFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            // Información del cliente (Alinear con más espacios)
            Paragraph clientInfo = new Paragraph(
                    "     NOMBRE CLIENTE: " + this.cliente.getNombre().toUpperCase() + " " + this.cliente.getApellidoPA().toUpperCase() + " " + this.cliente.getApellidoMA().toUpperCase() + "\n", normalFont);
            clientInfo.setAlignment(Element.ALIGN_LEFT);
            document.add(clientInfo);

            // Espacio para separar secciones
            document.add(new Paragraph("\n"));

            // Detalle de los artículos
            Paragraph articlesHeader = new Paragraph(
                    "     ARTICULO                     P C/U                - CANT                  TOTAL\n"
                    + "     ------------------------------------------------------------------------------------------\n", normalFont);
            articlesHeader.setAlignment(Element.ALIGN_LEFT);
            document.add(articlesHeader);

            // Artículos con más espacios para alinear
            Paragraph articles = new Paragraph(
                    "     BOLETO " + "            $" + funcion.getPrecio() + "                  -" + this.cantidadBoletos + "                   $" + (funcion.getPrecio().multiply(BigDecimal.valueOf(this.cantidadBoletos))) + "\n",
                    normalFont);
            articles.setAlignment(Element.ALIGN_LEFT);
            document.add(articles);

            // Espacio para separar secciones
            document.add(new Paragraph("\n"));

            // Resumen de compra
            Paragraph summary = new Paragraph(
                    "     TOTAL COMPRA:      " + (funcion.getPrecio().multiply(BigDecimal.valueOf(this.cantidadBoletos)))
                    + "     METODO PAGO:     " + venta.getMetodoPago().toString().toUpperCase() + "\n"
                    + "     FECHA:         " + utilerias.DateTimeUtil.formatearFechaHora(LocalDateTime.now()) + "\n"
                    + "     CIUDAD:       " + ciudad.getNombre().toUpperCase() + "\n", normalFont);
            summary.setAlignment(Element.ALIGN_LEFT);
            document.add(summary);

            // Espacio para separar secciones
            document.add(new Paragraph("\n"));

            // Espacio para separar secciones
            document.add(new Paragraph("\n"));

            // Mensaje de agradecimiento (Centrado con más espacios)
            Paragraph thanks = new Paragraph("******************************************************************\n"
                    + sucursal.getNombre().toUpperCase() + "\n"
                    + "\n******************************************************************\n", boldFont);
            thanks.setAlignment(Element.ALIGN_CENTER);
            document.add(thanks);
            try {
                Image logo;
                logo = Image.getInstance("src\\main\\resources\\imagenes\\QRreal.png"); // Cambia por la ruta de tu logo
                logo.scaleToFit(250, 250); // Tamaño del logo
                logo.setAlignment(Element.ALIGN_CENTER);
                document.add(logo);
            } catch (BadElementException ex) {
                Logger.getLogger(FrmCompraBoleto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FrmCompraBoleto.class.getName()).log(Level.SEVERE, null, ex);
            }
            // Cerrar el documento
            document.close();

            File pdfFile = new File(fileName);
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(pdfFile);
            } else {
                System.out.println("Abrir archivos no es soportado en este sistema.");
            }

            System.out.println("¡Boleto generado correctamente !");

        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilerias.MenuButton btnBoletos;
    private utilerias.MenuButton btnCancelar;
    private javax.swing.JButton btnCartel;
    private utilerias.MenuButton btnComprar;
    private utilerias.MenuButton btnInbox;
    private utilerias.MenuButton btnInicio;
    private utilerias.MenuButton btnPerfil;
    private utilerias.MenuButton btnRestarCantidad;
    private utilerias.MenuButton btnSucursales;
    private utilerias.MenuButton btnSumarCantidad;
    private utilerias.MenuButton btnTrailer;
    private javax.swing.JComboBox<Object> cbMetodosPago;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCantidadBoletos;
    private javax.swing.JLabel lblClasificacion;
    private javax.swing.JLabel lblClasificacionDescripcion;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblPaisOrigen;
    private javax.swing.JLabel lblTitulo;
    private utilerias.PanelConFondo panelConFondo1;
    private utilerias.PanelConFondo panelConFondo3;
    private utilerias.PanelConFondo panelConFondo6;
    // End of variables declaration//GEN-END:variables
}
