/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.CiudadDTO;
import dtos.ClienteDTO;
import dtos.GeneroDTO;
import dtos.PeliculaDTO;
import dtos.SucursalDTO;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import negocio.CiudadBO;
import negocio.FuncionBO;
import negocio.ICiudadBO;
import negocio.IFuncionBO;
import negocio.IGeneroBO;
import negocio.IPeliculaBO;
import negocio.ISucursalBO;
import negocio.ITicketBO;
import negocio.NegocioException;
import negocio.PeliculaBO;
import negocio.SucursalBO;
import negocio.TicketBO;
import persistencia.CiudadDAO;
import persistencia.ConexionBD;
import persistencia.FuncionDAO;
import persistencia.ICiudadDAO;
import persistencia.IConexionBD;
import persistencia.IFuncionDAO;
import persistencia.IPeliculaDAO;
import persistencia.ISucursalDAO;
import persistencia.ITicketDAO;
import persistencia.PeliculaDAO;
import persistencia.SucursalDAO;
import persistencia.TicketDAO;

/**
 *
 * @author carli
 */
public class FrmDetallePelicula extends javax.swing.JFrame {

    private IGeneroBO generoBO;
    private PeliculaDTO pelicula;
    private ClienteDTO cliente;
    private SucursalDTO sucursal;
    private CiudadDTO ciudad;
    private List<GeneroDTO> listaGeneros;

    public FrmDetallePelicula(IGeneroBO generoBO, PeliculaDTO pelicula, ClienteDTO cliente, SucursalDTO sucursal, CiudadDTO ciudad) {
        initComponents();
        this.generoBO = generoBO;
        this.pelicula = pelicula;
        this.cliente = cliente;
        this.sucursal = sucursal;
        this.ciudad = ciudad;
        System.out.println(pelicula.getId());
        cargarMetodosIniciales();
    }

    private void cargarMetodosIniciales() {
        this.setTitle(pelicula.getTitulo());
        this.setLocationRelativeTo(null);
        llenarComboBoxGenero();
        cargarDetallesPelicula();

    }

    private void cargarDetallesPelicula() {
        lblTitulo.setText(utilerias.Herramientas.textoConSaltosLinea(pelicula.getTitulo(), 5));
        jTextSinopsis.setText(pelicula.getSinopsis());
        lblPaisOrigen.setText(pelicula.getPais());
        lblDuracion.setText(pelicula.getDuracion() + " minutos");
        lblClasificacion.setText(pelicula.getClasificacion());

        if (pelicula.getClasificacionDescripcion().length() < 3) {
            lblClasificacionDescripcion.setText(" " + pelicula.getClasificacionDescripcion());

        } else {
            lblClasificacionDescripcion.setText(pelicula.getClasificacionDescripcion());
        }
        //Cargar Cartel Pelicula
        ImageIcon icon = new ImageIcon(pelicula.getCartel());
        Image scaledImage = icon.getImage().getScaledInstance(229, 353, Image.SCALE_SMOOTH);
        btnCartel.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInicio = new utilerias.MenuButton();
        btnSucursales = new utilerias.MenuButton();
        btnBoletos = new utilerias.MenuButton();
        btnInbox = new utilerias.MenuButton();
        btnPerfil = new utilerias.MenuButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnCartel = new javax.swing.JButton();
        btnTrailer = new utilerias.MenuButton();
        panelConFondo6 = new utilerias.PanelConFondo();
        jLabel17 = new javax.swing.JLabel();
        cbGeneros = new javax.swing.JComboBox<>();
        panelConFondo1 = new utilerias.PanelConFondo();
        jLabel6 = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        panelConFondo3 = new utilerias.PanelConFondo();
        lblClasificacion = new javax.swing.JLabel();
        lblClasificacionDescripcion = new javax.swing.JLabel();
        lblPaisOrigen = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        menuButton18 = new utilerias.MenuButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextSinopsis = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(33, 36, 59));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 65));
        jPanel3.setLayout(new java.awt.GridLayout(1, 5, 50, 0));

        btnInicio.setBorderPainted(false);
        btnInicio.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioSelected.png"))); // NOI18N
        btnInicio.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Inicio.png"))); // NOI18N
        btnInicio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InicioSelected.png"))); // NOI18N
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel3.add(btnInicio);

        btnSucursales.setBorderPainted(false);
        btnSucursales.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SucursalesSelected.png"))); // NOI18N
        btnSucursales.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sucursales.png"))); // NOI18N
        btnSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalesActionPerformed(evt);
            }
        });
        jPanel3.add(btnSucursales);

        btnBoletos.setBorderPainted(false);
        btnBoletos.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticketsSelected.png"))); // NOI18N
        btnBoletos.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tickets.png"))); // NOI18N
        btnBoletos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticketsSelected.png"))); // NOI18N
        btnBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletosActionPerformed(evt);
            }
        });
        jPanel3.add(btnBoletos);

        btnInbox.setBorderPainted(false);
        btnInbox.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inboxSelected.png"))); // NOI18N
        btnInbox.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inbox.png"))); // NOI18N
        btnInbox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inboxSelected.png"))); // NOI18N
        btnInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInboxActionPerformed(evt);
            }
        });
        jPanel3.add(btnInbox);

        btnPerfil.setBorderPainted(false);
        btnPerfil.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfilSelected.png"))); // NOI18N
        btnPerfil.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N
        btnPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfilSelected.png"))); // NOI18N
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel3.add(btnPerfil);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(36, 44, 99));
        jPanel4.setPreferredSize(new java.awt.Dimension(1280, 1280));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(36, 44, 99));

        jLabel1.setBackground(new java.awt.Color(36, 44, 99));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cinépolis_logo 1.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Line 7.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Top Gun Maverick");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(254, 254, 254))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(22, 22, 22))
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(36, 44, 99));
        jPanel8.setPreferredSize(new java.awt.Dimension(1280, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(36, 44, 99));

        jPanel9.setBackground(new java.awt.Color(36, 44, 99));

        jPanel10.setBackground(new java.awt.Color(36, 44, 99));

        btnCartel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3212c44f6aca4bc69d467d4614e6f3dc 1.png"))); // NOI18N
        btnCartel.setBorderPainted(false);
        btnCartel.setContentAreaFilled(false);
        btnCartel.setPreferredSize(new java.awt.Dimension(229, 353));
        btnCartel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartelActionPerformed(evt);
            }
        });

        btnTrailer.setBorderPainted(false);
        btnTrailer.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trailerSelected.png"))); // NOI18N
        btnTrailer.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trailer.png"))); // NOI18N
        btnTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrailerActionPerformed(evt);
            }
        });

        panelConFondo6.setPreferredSize(new java.awt.Dimension(169, 80));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/genero.png"))); // NOI18N

        cbGeneros.setBackground(new java.awt.Color(33, 36, 59));
        cbGeneros.setEditable(true);
        cbGeneros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbGeneros.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelConFondo6Layout = new javax.swing.GroupLayout(panelConFondo6);
        panelConFondo6.setLayout(panelConFondo6Layout);
        panelConFondo6Layout.setHorizontalGroup(
            panelConFondo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(cbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConFondo6Layout.setVerticalGroup(
            panelConFondo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo6Layout.createSequentialGroup()
                .addGroup(panelConFondo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConFondo6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel17))
                    .addGroup(panelConFondo6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(cbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        panelConFondo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelConFondo1.setPreferredSize(new java.awt.Dimension(169, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/duracion.png"))); // NOI18N

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setText("120 minutos");

        javax.swing.GroupLayout panelConFondo1Layout = new javax.swing.GroupLayout(panelConFondo1);
        panelConFondo1.setLayout(panelConFondo1Layout);
        panelConFondo1Layout.setHorizontalGroup(
            panelConFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(lblDuracion)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelConFondo1Layout.setVerticalGroup(
            panelConFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConFondo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDuracion)
                .addGap(27, 27, 27))
        );

        panelConFondo3.setPreferredSize(new java.awt.Dimension(169, 80));

        lblClasificacion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblClasificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblClasificacion.setText("RAA");

        lblClasificacionDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClasificacionDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblClasificacionDescripcion.setText("Adultos");

        javax.swing.GroupLayout panelConFondo3Layout = new javax.swing.GroupLayout(panelConFondo3);
        panelConFondo3.setLayout(panelConFondo3Layout);
        panelConFondo3Layout.setHorizontalGroup(
            panelConFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClasificacionDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConFondo3Layout.setVerticalGroup(
            panelConFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConFondo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelConFondo3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblClasificacionDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblPaisOrigen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPaisOrigen.setForeground(new java.awt.Color(255, 255, 255));
        lblPaisOrigen.setText("Estados Unidos");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCartel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConFondo3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(panelConFondo1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(panelConFondo6, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(lblPaisOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnTrailer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)))
                .addGap(20, 20, 20))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(btnCartel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTrailer, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConFondo6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConFondo1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jPanel16.setBackground(new java.awt.Color(36, 44, 99));

        menuButton18.setBackground(new java.awt.Color(36, 44, 99));
        menuButton18.setBorderPainted(false);
        menuButton18.setIconoSeleccionado(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprarTicketSelected.png"))); // NOI18N
        menuButton18.setIconoSimple(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprarTicket.png"))); // NOI18N
        menuButton18.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprarTicketSelected.png"))); // NOI18N
        menuButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton18ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jTextSinopsis.setEditable(false);
        jTextSinopsis.setBackground(new java.awt.Color(36, 44, 99));
        jTextSinopsis.setBorder(new EmptyBorder(0, 0, 0, 0));
        jTextSinopsis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        jTextSinopsis.setText("Después de más de treinta años de servicio como uno de los mejores aviadores de la Marina, Pete \"Maverick\" Mitchell está donde pertenece, desafiando los límites como un valiente piloto de pruebas y esquivando el ascenso de rango que lo mantendría en tierra. Cuando se encuentra entrenando a un destacamento de graduados de Top Gun para una misión especializada como ninguna que un piloto en vida haya presenciado, Maverick se encuentra con el teniente Bradley Bradshaw, alias: \"Rooster\", el hijo del difunto amigo de Maverick y Oficial de Interceptación de Radar, el teniente Nick Bradshaw, conocido como \"Goose\". Enfrentándose a un futuro incierto y confrontando los fantasmas de su pasado, Maverick es arrastrado a una confrontación con sus propios miedos más profundos, culminando en una misión que exige el sacrificio máximo de aquellos que serán elegidos para volarla.");
        jTextSinopsis.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextSinopsis);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(menuButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton18ActionPerformed
        IConexionBD conexion = new ConexionBD();
        IFuncionDAO funcionDAO = new FuncionDAO(conexion);
        IFuncionBO funcionBO = new FuncionBO(funcionDAO);

        FrmFuncionesPelicula funcionPelicula = new FrmFuncionesPelicula(funcionBO, pelicula, sucursal, cliente, ciudad);
        funcionPelicula.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuButton18ActionPerformed

    private void btnCartelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCartelActionPerformed

    private void btnTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrailerActionPerformed
        try {
            // Abre el enlace del tráiler en el navegador
            java.awt.Desktop.getDesktop().browse(new java.net.URI(pelicula.getLink_trailer()));
        } catch (java.io.IOException | java.net.URISyntaxException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir el tráiler: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTrailerActionPerformed

    private void btnSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalesActionPerformed
        IConexionBD conexion = new ConexionBD();

        ICiudadDAO ciudadDAO = new CiudadDAO(conexion);
        ISucursalDAO sucursalDAO = new SucursalDAO(conexion);

        ICiudadBO ciudadBO = new CiudadBO(ciudadDAO);
        ISucursalBO sucursalBO = new SucursalBO(sucursalDAO);

        FrmSucursales sucursales = new FrmSucursales(ciudadBO, sucursalBO, sucursal, cliente);
        sucursales.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSucursalesActionPerformed

    private void btnBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletosActionPerformed
        IConexionBD conexionBD = new ConexionBD();
        ITicketDAO ticketDAO = new TicketDAO(conexionBD);
        ITicketBO ticketBO = new TicketBO(ticketDAO);
        FrmBoletos boletos = new FrmBoletos(ticketBO, cliente, sucursal);
        boletos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBoletosActionPerformed

    private void btnInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInboxActionPerformed
        FrmInbox inbox = new FrmInbox();
        inbox.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInboxActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        FrmConfiguracionPerfil perfil = new FrmConfiguracionPerfil();
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        IConexionBD conexion = new ConexionBD();

        IPeliculaDAO peliculaDAO = new PeliculaDAO(conexion);
        ICiudadDAO ciudadDAO = new CiudadDAO(conexion);
        ISucursalDAO sucursalDAO = new SucursalDAO(conexion);

        IPeliculaBO peliculaBO = new PeliculaBO(peliculaDAO);
        ICiudadBO ciudadBO = new CiudadBO(ciudadDAO);
        ISucursalBO sucursalBO = new SucursalBO(sucursalDAO);
        FrmCatalogoSucursal catalogo = new FrmCatalogoSucursal(peliculaBO, ciudadBO, sucursalBO, sucursal, cliente);
        catalogo.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnInicioActionPerformed
    private void llenarComboBoxGenero() {
        try {
            listaGeneros = generoBO.listaGeneroPorPelicula(pelicula.getId(), true);

            for (GeneroDTO genero : listaGeneros) {
                cbGeneros.addItem(genero);
            }
        } catch (NegocioException ex) {
            Logger.getLogger(FrmCatalogoSucursal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilerias.MenuButton btnBoletos;
    private javax.swing.JButton btnCartel;
    private utilerias.MenuButton btnInbox;
    private utilerias.MenuButton btnInicio;
    private utilerias.MenuButton btnPerfil;
    private utilerias.MenuButton btnSucursales;
    private utilerias.MenuButton btnTrailer;
    private javax.swing.JComboBox<GeneroDTO> cbGeneros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextSinopsis;
    private javax.swing.JLabel lblClasificacion;
    private javax.swing.JLabel lblClasificacionDescripcion;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblPaisOrigen;
    private javax.swing.JLabel lblTitulo;
    private utilerias.MenuButton menuButton18;
    private utilerias.PanelConFondo panelConFondo1;
    private utilerias.PanelConFondo panelConFondo3;
    private utilerias.PanelConFondo panelConFondo6;
    // End of variables declaration//GEN-END:variables
}
