/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.CiudadDTO;
import dtos.ClienteDTO;
import dtos.ClienteTablaFiltroDTO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.ICiudadBO;
import negocio.NegocioException;
import negocio.IClienteBO;

/**
 *
 * @author Rios 233537
 */
public class frmEliminarClientes extends javax.swing.JFrame {

    FrmAdminClientes adminClientes;
    ClienteTablaFiltroDTO filtro;
    IClienteBO clienteNegocio;
    List<CiudadDTO> listaCiudades;
    ICiudadBO ciudad;
    ;
    int id;

    public frmEliminarClientes(FrmAdminClientes adminClientes, int id, IClienteBO clienteNegocio, ICiudadBO ciudad) throws NegocioException {
        initComponents(); // Inicializa los componentes del formulario
        this.adminClientes=adminClientes;
        this.clienteNegocio = clienteNegocio; // Asigna el negocio de clientes
        this.ciudad = ciudad;
        this.id = id;
        this.setTitle("Eliminar Cliente"); // Cambia el título del formulario
        metodosInciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        iDlabel = new javax.swing.JLabel();
        NombresTxt = new javax.swing.JTextField();
        Nacimientotxt = new javax.swing.JTextField();
        apellidoPATxt = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellidoMAtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Correotxt1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ciudadesCB = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(36, 44, 99));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iDlabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        iDlabel.setForeground(new java.awt.Color(255, 255, 255));
        iDlabel.setText("Eliminar Cliente");
        jPanel2.add(iDlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 260, -1));

        NombresTxt.setEditable(false);
        jPanel2.add(NombresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 184, 39));

        Nacimientotxt.setEditable(false);
        jPanel2.add(Nacimientotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 184, 39));

        apellidoPATxt.setEditable(false);
        jPanel2.add(apellidoPATxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 184, 39));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 157, 33));

        btnGuardar1.setText("Eliminar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 157, 33));

        jLabel2.setText("Nombres: *");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, -1));

        jLabel3.setText("Apellido Paterno: *");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("* Significan campos obligatorios");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        apellidoMAtxt.setEditable(false);
        jPanel2.add(apellidoMAtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 184, 39));

        jLabel5.setText("Apellido Materno: *");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        Correotxt1.setEditable(false);
        jPanel2.add(Correotxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 184, 39));

        jLabel6.setText("Fecha Nacimiento *");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 110, -1));

        jLabel8.setText("Ciudad *");
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, -1));

        jLabel9.setText("Correo *");
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, -1));

        ciudadesCB.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.add(ciudadesCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void metodosInciales() throws NegocioException {
        llenarComboBoxCiudades();
        metodoMostrarDatos();;
    }

    public void metodoMostrarDatos() throws NegocioException {
        try {
            ClienteDTO c = this.clienteNegocio.buscarClientePorId(this.id);
            NombresTxt.setText(c.getNombre());
            apellidoPATxt.setText(c.getApellidoPA());
            apellidoMAtxt.setText(c.getApellidoMA());
            Correotxt1.setText(c.getCorreo());
            Nacimientotxt.setText(c.getFechaNacimiento().toString());
        } catch (NegocioException ex) {
            System.out.println(ex.getMessage());
        }
    }

    ;
    
    private void llenarComboBoxCiudades() {
        try {
            listaCiudades = ciudad.listaCiudades();
            ClienteDTO cliente = this.clienteNegocio.buscarClientePorId(id);
            for (CiudadDTO ciudad : listaCiudades) {
                if (ciudad.getId() == cliente.getIdCiudad()) {
                    ciudadesCB.addItem(ciudad);
                    break;
                }
            }
            ciudadesCB.setEditable(false);
        } catch (NegocioException ex) {
            Logger.getLogger(FrmRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        try {
            this.clienteNegocio.eliminarCliente(id);
            this.adminClientes.cargarMetodosIniciales();
            dispose();
        } catch (NegocioException ex) {
            Logger.getLogger(FrmRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Correotxt1;
    private javax.swing.JTextField Nacimientotxt;
    private javax.swing.JTextField NombresTxt;
    private javax.swing.JTextField apellidoMAtxt;
    private javax.swing.JTextField apellidoPATxt;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JComboBox<CiudadDTO> ciudadesCB;
    private javax.swing.JLabel iDlabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
