/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.ClienteDTO;
import dtos.ClienteTablaFiltroDTO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.NegocioException;
import negocio.IClienteBO;

/**
 *
 * @author Rios 233537
 */
public class frmEliminarClientes extends javax.swing.JFrame {
    FrmCrudClientes pantallaPrincipal;
    ClienteDTO clienteDTO;
    ClienteTablaFiltroDTO filtro;
    IClienteBO clienteNegocio;

 
    public frmEliminarClientes(FrmCrudClientes pantallaPrincipal, IClienteBO clienteNegocio, ClienteDTO clienteDTO) {
    initComponents(); // Inicializa los componentes del formulario
    this.pantallaPrincipal = pantallaPrincipal; // Asigna la pantalla principal
    this.clienteNegocio = clienteNegocio; // Asigna el negocio de clientes
    this.clienteDTO = clienteDTO; // Asigna el cliente que se está editando
    this.setTitle("Eliminar Cliente"); // Cambia el título del formulario
    metodosInciales();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        iDlabel = new javax.swing.JLabel();
        NombresTxt = new javax.swing.JTextField();
        Nacimientotxt = new javax.swing.JTextField();
        apellidoPATxt = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellidoMAtxt1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Correotxt1 = new javax.swing.JTextField();
        Ubicaciontxt2 = new javax.swing.JTextField();
        Ciudadtxt3 = new javax.swing.JTextField();
        Contrasenatxt4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iDlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        iDlabel.setText("ID Cliente:");
        jPanel2.add(iDlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 166, -1));

        NombresTxt.setEditable(false);
        jPanel2.add(NombresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 184, 39));

        Nacimientotxt.setEditable(false);
        jPanel2.add(Nacimientotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 184, 39));

        apellidoPATxt.setEditable(false);
        jPanel2.add(apellidoPATxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 184, 39));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 157, 33));

        btnGuardar1.setText("Eliminar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 157, 33));

        jLabel1.setText("Contraseña");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 110, -1));

        jLabel2.setText("Nombres: *");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, -1));

        jLabel3.setText("Apellido Paterno: *");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, -1));

        jLabel4.setText("* Significan campos obligatorios");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        apellidoMAtxt1.setEditable(false);
        jPanel2.add(apellidoMAtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 184, 39));

        jLabel5.setText("Apellido Materno: *");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        Correotxt1.setEditable(false);
        jPanel2.add(Correotxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 184, 39));

        Ubicaciontxt2.setEditable(false);
        jPanel2.add(Ubicaciontxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 184, 39));

        Ciudadtxt3.setEditable(false);
        jPanel2.add(Ciudadtxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 184, 39));

        Contrasenatxt4.setEditable(false);
        jPanel2.add(Contrasenatxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 184, 39));

        jLabel6.setText("Nacimineto");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 110, -1));

        jLabel7.setText("Ubicacion");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, -1));

        jLabel8.setText("Ciudad");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 110, -1));

        jLabel9.setText("Correo");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void metodosInciales() {

        iDlabel.setText("ID Cliente: " + clienteDTO.getIdCliente());
        NombresTxt.setText(clienteDTO.getNombre());
        apellidoPATxt.setText(clienteDTO.getApellidoPA());
        apellidoMAtxt1.setText(clienteDTO.getApellidoMA());
        Correotxt1.setText(clienteDTO.getCorreo());
        Contrasenatxt4.setText(clienteDTO.getContraseña());
        Nacimientotxt.setText(clienteDTO.getFechaNacimiento().format(DateTimeFormatter.ISO_DATE));
        Ubicaciontxt2.setText(clienteDTO.getUbicacion());
        
    }
    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        String nombres = NombresTxt.getText();
        String apellidoPa = apellidoPATxt.getText();
        String apellidoMa = Nacimientotxt.getText();

        ClienteDTO edicionCliente = new ClienteDTO(clienteDTO.getIdCliente());
         int confirmacion = JOptionPane.showOptionDialog(this,
                    "¿Está seguro de que deseas eliminar al Cliente "+ clienteDTO.getIdCliente(),
                    "Confirmación de eliminacion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new Object[]{"Cancelar", "Confirmar"},
                    "Confirmar");

            // Si el usuario selecciona "Cancelar", no se hace nada
            if (confirmacion == JOptionPane.YES_OPTION) {
                return;
            }
       try {
        List<ClienteDTO> clientes = this.clienteNegocio.buscarPaginadosClienteTabla(10, 1); // Por ejemplo, límite 10, página 1

          if (clientes == null || clientes.isEmpty()) {
        // Si no hay clientes, puedes restar la página o manejar la lógica de paginación aquí
        pantallaPrincipal.estadoPagina();
         } else {
        // Cargar los clientes en la tabla si hay resultados
        this.pantallaPrincipal.cargarClientesEnTabla();
                     }
         dispose();
    
        } catch (NegocioException ex) {
         JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEliminarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEliminarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEliminarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEliminarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ciudadtxt3;
    private javax.swing.JTextField Contrasenatxt4;
    private javax.swing.JTextField Correotxt1;
    private javax.swing.JTextField Nacimientotxt;
    private javax.swing.JTextField NombresTxt;
    private javax.swing.JTextField Ubicaciontxt2;
    private javax.swing.JTextField apellidoMAtxt1;
    private javax.swing.JTextField apellidoPATxt;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JLabel iDlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
