/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


import dtos.PeliculaDTO;
import dtos.SalaDTO;
import dtos.SucursalDTO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.IPeliculaBO;
import negocio.ISalaBO;
import negocio.NegocioException;

/**
 *
 * @author rramirez
 */
public class FrmEditarPelicula extends javax.swing.JFrame {

    IPeliculaBO peliculaBO;
    int id;
    PeliculaDTO pelicula;
    

    /**
     * Creates new form FrmAgregarCliente
     */
    public FrmEditarPelicula(IPeliculaBO peliculaBO,int id)throws NegocioException{
        initComponents();
        this.peliculaBO = peliculaBO;
        this.id = id;
        metodoMostrarDatos();
    }

    public void metodoMostrarDatos(){
            try{
                PeliculaDTO c = this.peliculaBO.buscarPeliculaPorId(id);
                TxtCartel.setText(c.getCartel());
                TxtDuracion.setText(String.valueOf(c.getDuracion()));
                TxtLink.setText(c.getLink_trailer());
                TxtSinopsis.setText(c.getSinopsis());
                TxtTitulo.setText(c.getTitulo());
            }catch(NegocioException ex){
            System.out.println(ex.getMessage());
            }
            
            
            
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        LblAgregarCliente = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        TxtTitulo = new javax.swing.JTextField();
        LblPaterno = new javax.swing.JLabel();
        TxtPais = new javax.swing.JTextField();
        LblMaterno = new javax.swing.JLabel();
        TxtLink = new javax.swing.JTextField();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        LblPaterno1 = new javax.swing.JLabel();
        TxtDuracion = new javax.swing.JTextField();
        LblPaterno2 = new javax.swing.JLabel();
        TxtCartel = new javax.swing.JTextField();
        LblPaterno3 = new javax.swing.JLabel();
        TxtSinopsis = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LblAgregarCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LblAgregarCliente.setText("Editar Pelicula");

        LblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblNombre.setText("Titulo");

        LblPaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblPaterno.setText("Pais");

        LblMaterno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblMaterno.setText("Link del trailer");

        BtnAceptar.setBackground(new java.awt.Color(204, 204, 204));
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        LblPaterno1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblPaterno1.setText("Duracion");

        LblPaterno2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblPaterno2.setText("Cartel");

        LblPaterno3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblPaterno3.setText("Sinopsis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LblMaterno)
                                .addComponent(LblPaterno1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(LblNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblPaterno2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblPaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblPaterno3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtCartel)
                            .addComponent(TxtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtLink, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtPais, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtDuracion)
                            .addComponent(TxtSinopsis))
                        .addGap(18, 18, 18))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(LblAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 562, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPaterno3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
            String titulo = TxtTitulo.getText();
            String pais = TxtPais.getText();
            int duracion = Integer.parseInt(TxtDuracion.getText());
            String link = TxtLink.getText();
            String sinopsis = TxtSinopsis.getText();
            
            
            if (titulo.isEmpty() || duracion == 0 || link.isEmpty() || sinopsis.isEmpty() || pais.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Ingrese todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
           
        }
        try
        {
            PeliculaDTO c = this.peliculaBO.buscarPeliculaPorId(pelicula.getId());
            PeliculaDTO editar = new PeliculaDTO();
            this.peliculaBO.actualizarPelicula(editar);
            JOptionPane.showMessageDialog(this, "Registro modificado correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (NegocioException ex)
        {
            Logger.getLogger(FrmEditarPelicula.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        
    }//GEN-LAST:event_BtnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel LblAgregarCliente;
    private javax.swing.JLabel LblMaterno;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblPaterno;
    private javax.swing.JLabel LblPaterno1;
    private javax.swing.JLabel LblPaterno2;
    private javax.swing.JLabel LblPaterno3;
    private javax.swing.JTextField TxtCartel;
    private javax.swing.JTextField TxtDuracion;
    private javax.swing.JTextField TxtLink;
    private javax.swing.JTextField TxtPais;
    private javax.swing.JTextField TxtSinopsis;
    private javax.swing.JTextField TxtTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
